name: CI
on: [push]
jobs:
  build_and_test:
    name: nextbus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          tuolchain: stable
      - run: cargo build --release --all-features
